[project]
name = 'Consciousness-Backup-and-Restoration'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.distributed-consciousness-storage]
path = 'contracts/distributed-consciousness-storage.clar'
clarity_version = 2
epoch = 2.5

[contracts.mind-state-encoder]
path = 'contracts/mind-state-encoder.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
